name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.0.6
authors:
- Jonas Bark <jonas.bark@gmx.de>
- John Blanchard <jnblanchard@mac.com>
homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ">=0.6.0 <0.7.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: StripePaymentPlugin
        fileName: src/web/flutter_stripe_payment_web.dart
      android:
        pluginClass: StripePaymentPlugin
        package: de.jonasbark.stripepayment
      ios:
        pluginClass: StripePaymentPlugin

